// =============================================================
// IMPORT NOTION → ATS — Coller ce code dans la console du navigateur
// Ouvrir n'importe quelle page de l'ATS (ex: index.html) puis F12 > Console
// =============================================================

(async function importNotion() {
  console.log('🚀 Démarrage import Notion...');

  // --- Données brutes extraites des CSV Notion ---
  const RAW_ENTREPRISES = [
  {
    "nom": "Voltéo",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "Bordeaux",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Diocèse de Versailles",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "Paris",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Axa Millésimes Gestion",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "9 exceptional vineyards: Pichon Baron, Pibran, Suduiraut, Arlot, Quinta do Noval, Passadouro, Disznókő, Outpost & Platt",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "V8TE",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Vinci Construction",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "SoftatHome",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Compagnie des Alpes",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Trescal Group",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Agence Dn'D",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "groupe bonnefon",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "SORIBA",
    "secteur": "BTP",
    "taille": "51-200",
    "ca": "",
    "localisation": "Challans",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "http://www.soriba.fr",
    "telephone": "0251932301",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": "2026-02-04",
    "prochaine_relance": null
  },
  {
    "nom": "APLIX",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "VetPartners France",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Avenir Mutuelle",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Wibaie",
    "secteur": "BTP",
    "taille": "201-1000",
    "ca": "",
    "localisation": "Cholet",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "http://www.wibaie.fr",
    "telephone": "",
    "angle_approche": "",
    "source": "Linkedin",
    "notes": "Groupe Liebot",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Zoom in Zoom out",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "WeeFin",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "RCM",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "A5sys",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Pileje",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Fondation Cémavie",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "VMI Mixing Solutions",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Orisha",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "ADMR",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Brioche Pasquier",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "l'Hospitalet",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "BOUVET Menuiseries",
    "secteur": "BTP",
    "taille": "51-200",
    "ca": "250 M€+",
    "localisation": "La Membrolle sur Longuenée",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "http://www.menuiseries-bouvet.com",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Nickel",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "ALTYN",
    "secteur": "BTP",
    "taille": "201-1000",
    "ca": "",
    "localisation": "Nantes",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "www.altyn-groupe.com",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "energie",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Groupe Pautric",
    "secteur": "Retail",
    "taille": "1000+",
    "ca": "250 M€+",
    "localisation": "Nantes",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "https://groupepautric.com/",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "distribution automobile",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Ville de CHALLANS",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Vivalto Santé",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "La charcuterie Vendéenne - Petitgas",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "AGIR Recouvrement",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "GOZOKI",
    "secteur": "Industrie",
    "taille": "1000+",
    "ca": "250 M€+",
    "localisation": "Estillac",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "agro alimentaire",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Spie batignolles ETPO",
    "secteur": "BTP",
    "taille": "201-1000",
    "ca": "",
    "localisation": "Saint-Herblain",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "Linkedin",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Martin Technologies",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Groupe Laure",
    "secteur": "Transports",
    "taille": "201-1000",
    "ca": "",
    "localisation": "Saint Etienne de Montluc",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "https://groupelaure.fr/",
    "telephone": "02 40 85 70 70",
    "angle_approche": "",
    "source": "Linkedin",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Etablissements Sogal (CMAI)",
    "secteur": "BTP",
    "taille": "201-1000",
    "ca": "",
    "localisation": "Angers",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "http://www.cmai-goupe.com/",
    "telephone": "0241495450",
    "angle_approche": "",
    "source": "",
    "notes": "utilisent logiciel Sprit of TOD",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "LCA Construction Bois",
    "secteur": "BTP",
    "taille": "51-200",
    "ca": "20 -50 M€",
    "localisation": "Cholet",
    "priorite": "3 - Pertinent",
    "statut": "À cibler",
    "icp_fit": false,
    "site_web": "http://www.lca-construction.fr",
    "telephone": "0251416472",
    "angle_approche": "",
    "source": "Linkedin",
    "notes": "filiale de Bonnin Charbonneau",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "CRUARD CHARPENTE ET CONSTRUCTIONS BOIS",
    "secteur": "BTP",
    "taille": "51-200",
    "ca": "",
    "localisation": "Laval",
    "priorite": "",
    "statut": "À cibler",
    "icp_fit": false,
    "site_web": "http://cruard-charpente.com",
    "telephone": "0243981010",
    "angle_approche": "",
    "source": "Linkedin",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "EBTrans",
    "secteur": "Transports",
    "taille": "1000+",
    "ca": "",
    "localisation": "Nantes",
    "priorite": "3 - Pertinent",
    "statut": "À cibler",
    "icp_fit": false,
    "site_web": "http://ebtrans.com",
    "telephone": "",
    "angle_approche": "",
    "source": "Linkedin",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "SOLOC",
    "secteur": "BTP",
    "taille": "201-1000",
    "ca": "",
    "localisation": "Nantes",
    "priorite": "",
    "statut": "À cibler",
    "icp_fit": false,
    "site_web": "http://www.soloc.fr",
    "telephone": "0240574270",
    "angle_approche": "",
    "source": "Linkedin",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Giffard",
    "secteur": "Retail",
    "taille": "51-200",
    "ca": "50 - 100 M€",
    "localisation": "",
    "priorite": "",
    "statut": "À cibler",
    "icp_fit": false,
    "site_web": "http://www.giffard.com",
    "telephone": "",
    "angle_approche": "",
    "source": "Linkedin",
    "notes": "seulement un RSI depuis 8 ans, pas de DSI —- peut etre un peu tot mais à voir",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Finance Conseil",
    "secteur": "Finance",
    "taille": "201-1000",
    "ca": "50 - 100 M€",
    "localisation": "Beaucouzé",
    "priorite": "5 - Coeur de cible",
    "statut": "À cibler",
    "icp_fit": false,
    "site_web": "https://www.financeconseil.fr",
    "telephone": "",
    "angle_approche": "",
    "source": "Linkedin",
    "notes": "pas de DSI seul un Dir webmarketing et digital Quentin BODET",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "CASTEL",
    "secteur": "SaaS / Tech",
    "taille": "51-200",
    "ca": "20 -50 M€",
    "localisation": "Angers",
    "priorite": "5 - Coeur de cible",
    "statut": "À cibler",
    "icp_fit": true,
    "site_web": "https://www.castel.fr/castel/qui-sommes-nous/",
    "telephone": "+332 41 40 41 40",
    "angle_approche": "objectif de 40 M€ d’ici 5 ans, et s’inscrit dans un pôle tertiaire Urmet (Castel + MWS + Synchronic) à 53 M€ de CA pour environ 250 collaborateurs. Castel représente plus de la moitié de ce pôle, avec 146 collaborateurs dont ~100 sur le site de Neuillé. https://www.lejournaldesentreprises.com/article/le-fabricant-dinterphones-saumurois-castel-veut-accelerer-linternational-2122184",
    "source": "Linkedin",
    "notes": "Neuillé\n\nseulement un Administrateur systèmes et réseaux @ Trélazé (Sébastien Fortier)",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Maison BECAM",
    "secteur": "Retail",
    "taille": "201-1000",
    "ca": "20 -50 M€",
    "localisation": "Saint Barthélémy d'Anjou",
    "priorite": "5 - Coeur de cible",
    "statut": "À cibler",
    "icp_fit": true,
    "site_web": "http://maisonbecam.com",
    "telephone": "0241182096",
    "angle_approche": "",
    "source": "Linkedin",
    "notes": "En termes de niveau, on est sur un DSI groupe ou Directeur des Systèmes d’Information et du Digital avec :\n• périmètre groupe (siège + ateliers + réseau de boulangeries, y compris franchisés pour la partie outillage),\n• rattachement direct à la Direction générale,\n• rôle de conduite de la croissance (scaling du SI), plus que de simple maintien opérationnel.\nEn résumé : au vu des chiffres et de l’organisation, la fonction DSI est non seulement pertinente mais devient un levier stratégique pour accompagner le passage de 30 à 100 boulangeries",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "RIVARD",
    "secteur": "Industrie",
    "taille": "201-1000",
    "ca": "50 - 100 M€",
    "localisation": "Daumeray",
    "priorite": "5 - Coeur de cible",
    "statut": "À cibler",
    "icp_fit": true,
    "site_web": "http://www.rivard-international.com/fr/",
    "telephone": "0241336868",
    "angle_approche": "",
    "source": "Linkedin",
    "notes": "pour une ETI industrielle comme RIVARD (≈300 salariés, ≈50 M€ de CA, multi‑sites, filiale d’un groupe international, forte croissance et transformation industrielle), la présence d’un DSI est non seulement justifiée mais pratiquement indispensable pour sécuriser et accompagner le plan de développement à 5–10 ans.",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "Devillé ASC",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "nom": "BREGER",
    "secteur": "",
    "taille": "",
    "ca": "",
    "localisation": "",
    "priorite": "",
    "statut": "",
    "icp_fit": false,
    "site_web": "",
    "telephone": "",
    "angle_approche": "",
    "source": "",
    "notes": "",
    "dernier_contact": null,
    "prochaine_relance": null
  }
];

  const RAW_DECIDEURS = [
  {
    "prenom": "Héléne",
    "nom": "REILLE",
    "_ent_name": "Diocèse de Versailles",
    "fonction": "",
    "fonction_macro": "",
    "niveau_hierarchique": "",
    "role_decision": "",
    "perimetre": "France",
    "priorite_prospection": "",
    "niveau_relation": "",
    "email": "",
    "telephone": "",
    "linkedin": "",
    "localisation": "Paris",
    "notes_relation": "",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "prenom": "Jerome",
    "nom": "MADOC",
    "_ent_name": "GOZOKI",
    "fonction": "DG Groupe",
    "fonction_macro": "Direction générale",
    "niveau_hierarchique": "COMEX",
    "role_decision": "Décideur",
    "perimetre": "France",
    "priorite_prospection": "Moyenne",
    "niveau_relation": "Echange en cours",
    "email": "jerome_madoc@hotmail.com",
    "telephone": "",
    "linkedin": "https://www.linkedin.com/in/j%C3%A9r%C3%B4me-madoc-49a15b10/",
    "localisation": "Estillac",
    "notes_relation": "",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": "2026-01-29",
    "prochaine_relance": null
  },
  {
    "prenom": "Serge",
    "nom": "COMPAGNE",
    "_ent_name": "Voltéo",
    "fonction": "",
    "fonction_macro": "",
    "niveau_hierarchique": "",
    "role_decision": "",
    "perimetre": "France",
    "priorite_prospection": "",
    "niveau_relation": "",
    "email": "",
    "telephone": "",
    "linkedin": "",
    "localisation": "Bordeaux",
    "notes_relation": "",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "prenom": "Alexis",
    "nom": "CESBRON",
    "_ent_name": "Etablissements Sogal (CMAI)",
    "fonction": "HR Manager",
    "fonction_macro": "Ressources humaines",
    "niveau_hierarchique": "N-1",
    "role_decision": "Prescripteur",
    "perimetre": "France",
    "priorite_prospection": "",
    "niveau_relation": "Inconnu",
    "email": "",
    "telephone": "",
    "linkedin": "linkedin.com/in/alexis-cesbron-17962327",
    "localisation": "Angers",
    "notes_relation": "",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "prenom": "Isabelle",
    "nom": "SURZUR",
    "_ent_name": "Etablissements Sogal (CMAI)",
    "fonction": "DRH",
    "fonction_macro": "Ressources humaines",
    "niveau_hierarchique": "COMEX",
    "role_decision": "Influenceur",
    "perimetre": "France",
    "priorite_prospection": "Moyenne",
    "niveau_relation": "Inconnu",
    "email": "",
    "telephone": "",
    "linkedin": "linkedin.com/in/isabelle-surzur-a8a83182",
    "localisation": "Angers",
    "notes_relation": "",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "prenom": "Karine",
    "nom": "BOUHIER",
    "_ent_name": "LCA Construction Bois",
    "fonction": "DG Finance & RH",
    "fonction_macro": "Direction générale",
    "niveau_hierarchique": "COMEX",
    "role_decision": "Co-décideur",
    "perimetre": "France",
    "priorite_prospection": "",
    "niveau_relation": "Inconnu",
    "email": "",
    "telephone": "",
    "linkedin": "linkedin.com/in/karine-bouhier-667b2b86",
    "localisation": "Cholet",
    "notes_relation": "",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "prenom": "Edouard",
    "nom": "BONNIN",
    "_ent_name": "LCA Construction Bois",
    "fonction": "DG",
    "fonction_macro": "Direction générale",
    "niveau_hierarchique": "COMEX",
    "role_decision": "Co-décideur",
    "perimetre": "France",
    "priorite_prospection": "",
    "niveau_relation": "Inconnu",
    "email": "",
    "telephone": "",
    "linkedin": "linkedin.com/in/edouard-bonnin-lca-construction-bois",
    "localisation": "Cholet",
    "notes_relation": "",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "prenom": "André",
    "nom": "LEFEVRE",
    "_ent_name": "CRUARD CHARPENTE ET CONSTRUCTIONS BOIS",
    "fonction": "DG",
    "fonction_macro": "Direction générale",
    "niveau_hierarchique": "COMEX",
    "role_decision": "Décideur",
    "perimetre": "France",
    "priorite_prospection": "",
    "niveau_relation": "Inconnu",
    "email": "",
    "telephone": "",
    "linkedin": "linkedin.com/in/andré-lefevre-654517ab",
    "localisation": "Laval",
    "notes_relation": "",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "prenom": "Cyrille",
    "nom": "ROSE",
    "_ent_name": "SOLOC",
    "fonction": "Président",
    "fonction_macro": "Direction générale",
    "niveau_hierarchique": "COMEX",
    "role_decision": "Décideur",
    "perimetre": "Europe",
    "priorite_prospection": "",
    "niveau_relation": "Inconnu",
    "email": "",
    "telephone": "",
    "linkedin": "https://www.linkedin.com/in/cyrille-rose-a74384103",
    "localisation": "Nantes",
    "notes_relation": "",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "prenom": "Pierre",
    "nom": "JOUANNEAU-GIFFARD",
    "_ent_name": "Giffard",
    "fonction": "DG",
    "fonction_macro": "Direction générale",
    "niveau_hierarchique": "COMEX",
    "role_decision": "Co-décideur",
    "perimetre": "Europe",
    "priorite_prospection": "Haute",
    "niveau_relation": "Inconnu",
    "email": "",
    "telephone": "",
    "linkedin": "https://www.linkedin.com/in/pierre-jouanneau-giffard-a2760b67",
    "localisation": "",
    "notes_relation": "",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "prenom": "Jérémy",
    "nom": "MIGNÉ",
    "_ent_name": "Finance Conseil",
    "fonction": "PDT Groupe",
    "fonction_macro": "Direction générale",
    "niveau_hierarchique": "COMEX",
    "role_decision": "Décideur",
    "perimetre": "France",
    "priorite_prospection": "Haute",
    "niveau_relation": "Inconnu",
    "email": "j.migne@financeconseil.fr",
    "telephone": "+33678768640",
    "linkedin": "https://www.linkedin.com/in/jeremymigne",
    "localisation": "Beaucouzé",
    "notes_relation": "+33678768640",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "prenom": "Ali",
    "nom": "BAYDOUN",
    "_ent_name": "CASTEL",
    "fonction": "Director @ URMET Tertiary",
    "fonction_macro": "Direction générale",
    "niveau_hierarchique": "COMEX",
    "role_decision": "Décideur",
    "perimetre": "Europe",
    "priorite_prospection": "Haute",
    "niveau_relation": "Inconnu",
    "email": "ali.baydoun@synchronic.fr",
    "telephone": "+33679502875",
    "linkedin": "https://www.linkedin.com/in/ali-baydoun-2876a2",
    "localisation": "Angers",
    "notes_relation": "+33241404140",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "prenom": "Nicolas",
    "nom": "BECAM",
    "_ent_name": "Maison BECAM",
    "fonction": "PDG",
    "fonction_macro": "Direction générale",
    "niveau_hierarchique": "COMEX",
    "role_decision": "Décideur",
    "perimetre": "France",
    "priorite_prospection": "Haute",
    "niveau_relation": "Contacté",
    "email": "nicolas.becam@maisonbecam.com",
    "telephone": "+33618350511",
    "linkedin": "https://www.linkedin.com/in/nicolasbecamboulangerpatissier/",
    "localisation": "Saint Barthélémy d'Anjou",
    "notes_relation": "",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": null,
    "prochaine_relance": null
  },
  {
    "prenom": "Jean-Michel",
    "nom": "THION",
    "_ent_name": "RIVARD",
    "fonction": "DG",
    "fonction_macro": "Direction générale",
    "niveau_hierarchique": "COMEX",
    "role_decision": "Décideur",
    "perimetre": "Europe",
    "priorite_prospection": "Haute",
    "niveau_relation": "",
    "email": "jean-michel.thion@rivard.fr",
    "telephone": "+33.6.66.81.66.29",
    "linkedin": "https://www.linkedin.com/in/jean-michel-thion-business",
    "localisation": "Daumeray",
    "notes_relation": "33625428981",
    "manager_direct_id": null,
    "missions_ids": [],
    "profil_candidat_id": null,
    "a_relancer": false,
    "dernier_contact": null,
    "prochaine_relance": null
  }
];

  // --- Helpers ---
  const genId = (prefix) => prefix + '_' + Date.now().toString(36) + Math.random().toString(36).substr(2, 5);
  const now = new Date().toISOString().split('T')[0];

  // --- 1) IMPORT ENTREPRISES ---
  console.log('📦 Chargement entreprises existantes...');
  const existingEnt = await API.fetchBin('entreprises') || [];
  const existingEntNames = new Set(existingEnt.map(e => (e.nom || '').toLowerCase()));

  // Map nom → id pour les entreprises (existantes + nouvelles)
  const entNameToId = {};
  existingEnt.forEach(e => { entNameToId[(e.nom || '').toLowerCase()] = e.id; });

  let addedEnt = 0, skippedEnt = 0;
  for (const ent of RAW_ENTREPRISES) {
    if (existingEntNames.has(ent.nom.toLowerCase())) {
      skippedEnt++;
      continue;
    }
    const record = { ...ent, id: genId('ent'), created_at: now, updated_at: now };
    existingEnt.push(record);
    entNameToId[ent.nom.toLowerCase()] = record.id;
    addedEnt++;
  }

  console.log(`✅ Entreprises : ${addedEnt} ajoutées, ${skippedEnt} déjà existantes`);
  await API.updateBin('entreprises', existingEnt);
  console.log('💾 Entreprises sauvegardées dans JSONBin');

  // --- 2) IMPORT DÉCIDEURS ---
  console.log('📦 Chargement décideurs existants...');
  const existingDec = await API.fetchBin('decideurs') || [];
  const existingDecNames = new Set(existingDec.map(d => `${(d.prenom||'').toLowerCase()} ${(d.nom||'').toLowerCase()}`));

  let addedDec = 0, skippedDec = 0, linkedDec = 0;
  for (const dec of RAW_DECIDEURS) {
    const key = `${dec.prenom.toLowerCase()} ${dec.nom.toLowerCase()}`;
    if (existingDecNames.has(key)) {
      skippedDec++;
      continue;
    }
    // Résoudre entreprise_id depuis le nom
    const entreprise_id = entNameToId[(dec._ent_name || '').toLowerCase()] || '';
    if (entreprise_id) linkedDec++;

    const record = {
      ...dec,
      id: genId('dec'),
      entreprise_id,
      created_at: now,
      updated_at: now,
    };
    delete record._ent_name;
    existingDec.push(record);
    addedDec++;
  }

  console.log(`✅ Décideurs : ${addedDec} ajoutés, ${skippedDec} déjà existants`);
  console.log(`🔗 Liaisons décideur→entreprise : ${linkedDec}/${addedDec} résolues`);
  await API.updateBin('decideurs', existingDec);
  console.log('💾 Décideurs sauvegardés dans JSONBin');

  // --- 3) Rafraîchir le cache local ---
  localStorage.removeItem('ats_data_entreprises');
  localStorage.removeItem('ats_data_decideurs');
  console.log('🧹 Cache local vidé');

  console.log('');
  console.log('='.repeat(50));
  console.log(`RÉSUMÉ :`);
  console.log(`  Entreprises : ${addedEnt} nouvelles (${existingEnt.length} total)`);
  console.log(`  Décideurs   : ${addedDec} nouveaux (${existingDec.length} total)`);
  console.log(`  Liaisons     : ${linkedDec}/${addedDec} décideurs liés à leur entreprise`);
  console.log('='.repeat(50));
  console.log('✅ Import terminé ! Rafraîchis la page (F5) pour voir les données.');
})();
